baseurl = "http://chungwei.github.io/"
languageCode = "zh"
duoshuoShortname = "chungwei"

[taxonomies]
    tag = "tags"
    tutorial = "tutorials"
    category = "categories"

[params]
    showglobe = true

    github = "https://github.com/chungwei"
    email = "wei.chungwei@gmail.com"
    profilepic = "img/profile.png"
    
    title = "酒肉穿肠过"
    subtitle = "　"
    
    [[params.navlinks]]
    name = "关于我"
    url = "about"
    
    [[params.navlinks]]
    name = "主页"
    url = ""

[permalinks]
  post = "/:year/:month/:day/:filename/" # optional
