baseurl = "http://chungwei.github.io/"
languageCode = "zh-CN"
title = "Life is Good"
toc = true
paginate = 3

[params]
    TableOfContents = "dddddd的哈哈哈哈哈"

[[menu.main]]
    name = "关于我"
    pre = "<i class='fa fa-heart'></i>"
    weight = 0
    identifier = "about"
    url = "/about/"

[[menu.main]] 
    name = "首页"
    pre = "<i class='fa fa-road'></i>"
    weight = -10
    identifier = "home"
    url = "/"
